name: Continuous Integration
on:
  push:
    branches:
      - master
    paths:
      - 'java/*'
  pull_request:
    paths:
      - 'java/*'

jobs:
  compile:
    name: Compile Java Module
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./java
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Compile Tests
        run: make compile compile-test

      - name: Validate
        run: make verify
