name: 'Python - Tests'

on:
  push:
    branches: [ master ]
    paths:
      - python/**
  pull_request:
    branches: [ master ]
    paths:
      - python/**
  workflow_dispatch:

defaults:
  run:
    working-directory: ./python
jobs:
  test:
    name: Python - Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run linters
        run: |
          make check

      - name: Run unit tests
        run: |
          make unit-test

      - name: Run integration tests
        run: |
          make integration-test

      - name: Stop the cluster
        if: ${{ always() }}
        run: |
         make scylla-kill
